---
version: "3"
services:
 devopsdb:
   image: ajay265dockerhub/javapro:dbv1
   ports:
     - "3306:3306"

 application:
   image: ajay265dockerhub/javapro:appv1
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
